version: '2.1'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=cohesion_content
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=cohesion_content
    ports:
      - "5432:5432"

  migrate:
    build: ./migrations/
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/cohesion_content
      - FLYWAY_USER=cohesion_content
      - FLYWAY_PASSWORD=1234
    depends_on:
      - postgres

  localstack:
    image: localstack/localstack:1.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foo

  mock-kinesis:
    build:
      context: .
      dockerfile: mock_services/kinesis/Dockerfile
    ports:
      - "8003:8003"
