version: '2.1'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=gokinesis
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=gokinesis
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:1.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=foo

  mock-kinesis:
    build:
      context: .
      dockerfile: mock_services/kinesis/Dockerfile
    ports:
      - "8003:8003"
